controller_manager:
  ros__parameters:
    update_rate: 20

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    left_wheel_controller:
      type: velocity_controllers/JointGroupVelocityController
    right_wheel_controller:
      type: velocity_controllers/JointGroupVelocityController
    back_wheel_controller:
      type: velocity_controllers/JointGroupVelocityController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

right_arm_controller:
  ros__parameters:
    joints:
      - R_Rotation
      - R_Pitch
      - R_Elbow
      - R_Wrist_Pitch
      - R_Wrist_Roll
      - R_Jaw
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    
    constraints:
      stopped_velocity_tolerance: 0.02
      goal_time: 0.0

left_arm_controller:
  ros__parameters:
    joints:
      - L_Rotation
      - L_Pitch
      - L_Elbow
      - L_Wrist_Pitch
      - L_Wrist_Roll
      - L_Jaw
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    
    constraints:
      stopped_velocity_tolerance: 0.02
      goal_time: 0.0

head_controller:
  ros__parameters:
    joints:
      - base_to_cam
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    
    constraints:
      stopped_velocity_tolerance: 0.02
      goal_time: 0.0


left_wheel_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
    command_interfaces:
      - velocity

right_wheel_controller:
  ros__parameters:
    joints:
      - right_wheel_joint
    command_interfaces:
      - velocity

back_wheel_controller:
  ros__parameters:
    joints:
      - back_wheel_joint
    command_interfaces:
      - velocity


joint_state_broadcaster:
  ros__parameters:
    {}